/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ucr.ac.cr.view;

import java.awt.event.ActionListener;

/**
 *
 * @author Jason
 */
public class BurritosGUI extends javax.swing.JFrame {

    private int burrito;
    /**
     * Creates new form BurritosGUI
     */
    public BurritosGUI() {
        initComponents();
        this.setResizable(false);
        this.setLocationRelativeTo(null);
        burrito=1;
        inicio();
    }

    public void listen(ActionListener controller)
    {
        this.btnExit.addActionListener(controller);
        this.btnNext.addActionListener(controller);
    }
    
    public void nextBurrito(){
         burrito++;
         
         if(burrito==1){
            inicio();
         }
         if(burrito==2){
             lbNameBurritos.setText("Burrito Chimichanga");
             lbBurritoBowl.setVisible(false);
             lbBurritoChimichanga.setVisible(true);
             lbPorkBurrito.setVisible(false);
             lbBigCheddarBurrito.setVisible(false);
             lbChickenBurrito.setVisible(false);
             
         }
         if(burrito==3){
             lbNameBurritos.setText("Pork Burrito");
             lbBurritoBowl.setVisible(false);
             lbBurritoChimichanga.setVisible(false);
             lbPorkBurrito.setVisible(true);
             lbBigCheddarBurrito.setVisible(false);
             lbChickenBurrito.setVisible(false);
             
         }
         if(burrito==4){
             lbNameBurritos.setText("Big Cheddar Burrito");
             lbBurritoBowl.setVisible(false);
             lbBurritoChimichanga.setVisible(false);
             lbPorkBurrito.setVisible(false);
             lbBigCheddarBurrito.setVisible(true);
             lbChickenBurrito.setVisible(false);
             
         }
         if(burrito==5){
             lbNameBurritos.setText("Chicken Burrito");
             lbBurritoBowl.setVisible(false);
             lbBurritoChimichanga.setVisible(false);
             lbPorkBurrito.setVisible(false);
             lbBigCheddarBurrito.setVisible(false);
             lbChickenBurrito.setVisible(true);
             
         }
         if(burrito==6){
             inicio();
             burrito=1;
         }
         
     }
     
     public void inicio(){
          lbNameBurritos.setText("Burrito bowl");
             lbBurritoBowl.setVisible(true);
             lbBurritoChimichanga.setVisible(false);
             lbPorkBurrito.setVisible(false);
             lbBigCheddarBurrito.setVisible(false);
             lbChickenBurrito.setVisible(false);
     }
     
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbNameBurritos = new javax.swing.JLabel();
        lbBackgroundRed1 = new javax.swing.JLabel();
        btnExit = new javax.swing.JButton();
        btnNext = new javax.swing.JButton();
        lbBackgroundRed2 = new javax.swing.JLabel();
        lbBurritoBowl = new javax.swing.JLabel();
        lbBurritoChimichanga = new javax.swing.JLabel();
        lbPorkBurrito = new javax.swing.JLabel();
        lbBigCheddarBurrito = new javax.swing.JLabel();
        lbChickenBurrito = new javax.swing.JLabel();
        lbBackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbNameBurritos.setBackground(new java.awt.Color(255, 255, 255));
        lbNameBurritos.setFont(new java.awt.Font("Trebuchet MS", 3, 36)); // NOI18N
        lbNameBurritos.setForeground(new java.awt.Color(238, 236, 208));
        lbNameBurritos.setText("Burritos");
        getContentPane().add(lbNameBurritos, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 510, 39));

        lbBackgroundRed1.setBackground(new java.awt.Color(160, 40, 38));
        lbBackgroundRed1.setOpaque(true);
        getContentPane().add(lbBackgroundRed1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 560, 60));

        btnExit.setBackground(new java.awt.Color(149, 38, 36));
        btnExit.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        btnExit.setForeground(new java.awt.Color(238, 236, 208));
        btnExit.setText("Exit");
        btnExit.setBorder(null);
        btnExit.setBorderPainted(false);
        btnExit.setOpaque(true);
        getContentPane().add(btnExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 490, 60, 40));

        btnNext.setBackground(new java.awt.Color(149, 38, 36));
        btnNext.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        btnNext.setForeground(new java.awt.Color(238, 236, 208));
        btnNext.setText("Next");
        btnNext.setBorder(null);
        btnNext.setBorderPainted(false);
        btnNext.setFocusPainted(false);
        getContentPane().add(btnNext, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 490, 70, 40));

        lbBackgroundRed2.setBackground(new java.awt.Color(160, 40, 38));
        lbBackgroundRed2.setOpaque(true);
        getContentPane().add(lbBackgroundRed2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 480, 560, 60));

        lbBurritoBowl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Burrito bowl.jpg"))); // NOI18N
        getContentPane().add(lbBurritoBowl, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, -1, 400));

        lbBurritoChimichanga.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Burrito chimichanga.jpg"))); // NOI18N
        getContentPane().add(lbBurritoChimichanga, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, -1, 400));

        lbPorkBurrito.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Pork burrito.jpg"))); // NOI18N
        getContentPane().add(lbPorkBurrito, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, -1, 400));

        lbBigCheddarBurrito.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/big cheddar.jpg"))); // NOI18N
        getContentPane().add(lbBigCheddarBurrito, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, -1, 400));

        lbChickenBurrito.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/chicken burrito.jpg"))); // NOI18N
        getContentPane().add(lbChickenBurrito, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, -1, 400));

        lbBackground.setBackground(new java.awt.Color(255, 255, 255));
        lbBackground.setOpaque(true);
        getContentPane().add(lbBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 560, 540));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnNext;
    private javax.swing.JLabel lbBackground;
    private javax.swing.JLabel lbBackgroundRed1;
    private javax.swing.JLabel lbBackgroundRed2;
    private javax.swing.JLabel lbBigCheddarBurrito;
    private javax.swing.JLabel lbBurritoBowl;
    private javax.swing.JLabel lbBurritoChimichanga;
    private javax.swing.JLabel lbChickenBurrito;
    private javax.swing.JLabel lbNameBurritos;
    private javax.swing.JLabel lbPorkBurrito;
    // End of variables declaration//GEN-END:variables
}
