/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ucr.ac.cr.view;

import java.awt.event.ActionListener;

/**
 *
 * @author Jason
 */
public class TacosGUI extends javax.swing.JFrame {

    /**
     * Creates new form TacosGUI
     */
    private int taco;
    public TacosGUI() {
        initComponents();
       this.setResizable(false);
        this.setLocationRelativeTo(null);
        taco=1;
        inicio();
    }

     
     
      public void listen(ActionListener controller)
    {
        this.btnExit.addActionListener(controller);
        this.btnNext.addActionListener(controller);
    }
     
     public void nextTaco(){
         taco++;
         
         if(taco==1){
            inicio();
         }
         if(taco==2){
             lbNameTaco.setText("Space Rancher");
             lbPotatoTaco.setVisible(false);
             lbSpaceRancher.setVisible(true);
             lbBlueBerryFilds.setVisible(false);
             lbPigTaco.setVisible(false);
             
         }
         if(taco==3){
             lbNameTaco.setText("Blue Berry Filds");
             lbPotatoTaco.setVisible(false);
             lbSpaceRancher.setVisible(false);
             lbBlueBerryFilds.setVisible(true);
             lbPigTaco.setVisible(false);
             
         }
         if(taco==4){
             lbNameTaco.setText("Pig Taco");
             lbPotatoTaco.setVisible(false);
             lbSpaceRancher.setVisible(false);
             lbBlueBerryFilds.setVisible(false);
             lbPigTaco.setVisible(true);
             
         }
         if(taco==5){
             inicio();
             taco=1;
         }
         
     }
     
     public void inicio(){
          lbNameTaco.setText("Potato Taco");
             lbPotatoTaco.setVisible(true);
             lbSpaceRancher.setVisible(false);
             lbBlueBerryFilds.setVisible(false);
             lbPigTaco.setVisible(false);
     }
     
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbNameTaco = new javax.swing.JLabel();
        lbBackgroundRed1 = new javax.swing.JLabel();
        btnExit = new javax.swing.JButton();
        btnNext = new javax.swing.JButton();
        lbBackgroundRed2 = new javax.swing.JLabel();
        lbPotatoTaco = new javax.swing.JLabel();
        lbSpaceRancher = new javax.swing.JLabel();
        lbBlueBerryFilds = new javax.swing.JLabel();
        lbPigTaco = new javax.swing.JLabel();
        lbBackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbNameTaco.setFont(new java.awt.Font("Trebuchet MS", 3, 36)); // NOI18N
        lbNameTaco.setForeground(new java.awt.Color(238, 236, 208));
        lbNameTaco.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbNameTaco.setText("Tacos");
        getContentPane().add(lbNameTaco, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 440, 40));

        lbBackgroundRed1.setBackground(new java.awt.Color(160, 40, 38));
        lbBackgroundRed1.setOpaque(true);
        getContentPane().add(lbBackgroundRed1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 510, 60));

        btnExit.setBackground(new java.awt.Color(149, 38, 36));
        btnExit.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        btnExit.setForeground(new java.awt.Color(238, 236, 208));
        btnExit.setText("Next");
        btnExit.setBorder(null);
        btnExit.setBorderPainted(false);
        btnExit.setFocusPainted(false);
        btnExit.setOpaque(true);
        getContentPane().add(btnExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 490, 70, 40));

        btnNext.setBackground(new java.awt.Color(149, 38, 36));
        btnNext.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        btnNext.setForeground(new java.awt.Color(238, 236, 208));
        btnNext.setText("Exit");
        btnNext.setBorder(null);
        btnNext.setBorderPainted(false);
        btnNext.setFocusPainted(false);
        btnNext.setOpaque(true);
        getContentPane().add(btnNext, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 490, 60, 40));

        lbBackgroundRed2.setBackground(new java.awt.Color(160, 40, 38));
        lbBackgroundRed2.setOpaque(true);
        getContentPane().add(lbBackgroundRed2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 470, 510, 70));

        lbPotatoTaco.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/potatoTaco.jpeg"))); // NOI18N
        getContentPane().add(lbPotatoTaco, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, -1, 390));

        lbSpaceRancher.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Space Rancher_taco.jpg"))); // NOI18N
        getContentPane().add(lbSpaceRancher, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, -1, 390));

        lbBlueBerryFilds.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Blueberryfilds_taco.jpg"))); // NOI18N
        getContentPane().add(lbBlueBerryFilds, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, -1, 390));

        lbPigTaco.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Pig taco.jpg"))); // NOI18N
        getContentPane().add(lbPigTaco, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, -1, 390));

        lbBackground.setBackground(new java.awt.Color(255, 255, 255));
        lbBackground.setOpaque(true);
        getContentPane().add(lbBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 510, 540));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnNext;
    private javax.swing.JLabel lbBackground;
    private javax.swing.JLabel lbBackgroundRed1;
    private javax.swing.JLabel lbBackgroundRed2;
    private javax.swing.JLabel lbBlueBerryFilds;
    private javax.swing.JLabel lbNameTaco;
    private javax.swing.JLabel lbPigTaco;
    private javax.swing.JLabel lbPotatoTaco;
    private javax.swing.JLabel lbSpaceRancher;
    // End of variables declaration//GEN-END:variables
}
